### PR TITLE
Add left/right/center align support to wrapped text

### PR DESCRIPTION
**Pull request by Starbuck5**
Hello. This covers part of #160.

I probably did plenty of stuff wrong.

The challenging bit was getting the underlines and strikethroughs to move with the text, so I added another parameter to drawLine that moves everything over on the x.

### CODE REVIEW

**Comment by 1bsyl** [comment]
I haven't tried it, but at first, it looks neat. 
just: 
- remove the "printf("setting font align=%i\n", align);"
- align the "if else" condition

please test with valgrind, strike / underline and Blended / Shaded / Mono

**Comment by Starbuck5** [comment]
> remove the "printf("setting font align=%i\n", align);"

Ah, I hoped I could force push fast enough that no one would notice. 😅

I get what you mean with the `if/else` align.

I might have trouble with valgrind on this system, but this should be good with memory because I didn't do any mallocs.

**Comment by 1bsyl** [comment]
@Starbuck5 just re-align the "if else if" but that's not a big deal
I am going to try the patch

**Comment by sezero** [comment]
Removing the extra comment from the commit message would be good.

**Comment by Starbuck5** [comment]
> Removing the extra comment from the commit message would be good.

Oh sorry, that was an artifact of my squash. Not intentional.

**Comment by 1bsyl** [comment]
It seems to me it crashes when rendering a corner case.

Actually this is an "Invalid write of size 4"

This happen in Draw_Line (
SDL_memset4 (SDL_stdinc.h:453)
==24065==    by 0x4A96084: Draw_Line (SDL_ttf.c:927) )

align: right
wrappedLenght: 661 (eg big)
string:   "="
Blended
font: /system/fonts_AndroidN_Preview/DancingScript-Regular.ttf

I cannot provide a real testcase, I use a test app. with fuzzing. [SDL_ttf_testapp.c.txt](https://github.com/libsdl-org/SDL_ttf/files/7838253/SDL_ttf_testapp.c.txt)

(you need to fill with font path insides), 
F1= help
press 'r' to do random rendering
( comment out the line 615, this is to 'replay' a crash configuration)

I may have a closer look, but not right now!

**Comment by 1bsyl** [comment]
@Starbuck5 
I looked again, and we need to change 'wrapLength' to 'width'
because if the surface won't be wider that wrapLength for sure, it may be smaller!
```
        if (font->horizontal_align == TTF_ALIGN_RIGHT) {
            xoffset = width - line_width;
        } else if (font->horizontal_align == TTF_ALIGN_CENTER) {
            xoffset = width / 2 - line_width / 2;
        } else {
            xoffset = 0;
        }
```
I'll run the fuzzing in background to detect any other issue ... 

Otherwise, maybe we should rename the function so that it's clear the alignment is for the Wrapped methods ? 
Any suggestion @slouken ?

**Comment by Starbuck5** [comment]
> surface won't be wider that wrapLength for sure, it may be smaller!

Ah, I was assuming it was guaranteed at the wrapLength width.

For API, maybe it should be `TTF_SetFontWrappedAlign`.

**Comment by Starbuck5** [comment]
> because if the surface won't be wider that wrapLength for sure, it may be smaller!

Oh, this might be a problem for right and center aligned text. For example, if it's right aligned at wrapLength=500, it should end at the 500th pixel, not the last pixel of whatever the longest width was.

**Comment by 1bsyl** [comment]
> > because if the surface won't be wider that wrapLength for sure, it may be smaller!
> 
> Oh, this might be a problem for right and center aligned text. For example, if it's right aligned at wrapLength=500, it should end at the 500th pixel, not the last pixel of whatever the longest width was.

yes, then add: 

line ~3510

```patch
             /* Don't go above wrapLength if you have only 1 line which hasn't been cut */
             if (font->horizontal_align == TTF_ALIGN_RIGHT) {
                 width = SDL_min((int)wrapLength, width);
             }
+            if (font->horizontal_align != TTF_ALIGN_RIGHT) {
+                width = wrapLength;
+            }
```

so that it creates a wrapLength surface

**Comment by 1bsyl** [comment]
for me it passes the valgrind/fuzzing testing with 100 000 wrapped string with no issue detected.

**Comment by Starbuck5** [comment]
> for me it passes the valgrind/fuzzing testing with 100 000 wrapped strings with no issue detected.

Nice!

I pushed some more changes. One of which was directly suggested by you. The other one I changed up a bit.

Since the surface can only be less than wrapLength if it's a single line, and only if it's ALIGN_LEFT, it seemed simpler to have it always be wrapLength wide. Maybe that would also be convenient to people calling the function.

New problem I found is that it no longer handles wrapLength = 0 as it used to. I don't think it's from this latest commit.

**Comment by 1bsyl** [comment]
Indeed I fixed the issue with wraplength = 0;
https://github.com/libsdl-org/SDL_ttf/commit/3e702ed9bf400b0a72534f144b8bec46ee0416cb

Please keep the legacy behavior so that the surface may be < wrapLength if align is left

**Comment by Starbuck5** [comment]
> Please keep the legacy behavior so that the surface may be < wrapLength if align is left

Alrighty.

@1bsyl I believe this is now logically equivalent to how it was before. It can only be less than wrapLength if it's 1 line and if it's left aligned.

**Comment by 1bsyl** [comment]
Yes, this seems ok to me !
just the function name, and if we want to add a function to store a meta style struct as @slouken suggested

**Comment by Starbuck5** [comment]
Alright, I'll change the name to `TTF_SetFontWrappedAlign`, if that's alright. It's more descriptive than what I've got in now.

The funny thing about the struct idea is that I'm implementing this so I can use it downstream in Pygame, and I was planning to expose that as an extra "layout" dictionary argument.

But on this level, with just a couple of them, I think it would be simpler (for us and for the users) to do it with functions as I've done here.

**Comment by 1bsyl** [comment]
@Starbuck5 let's wait for @slouken last word so you don't change back and forth multiple times :)

**Comment by 1bsyl** [comment]
Don't worry, we can "squash and merge" in the end

**Comment by Starbuck5** [comment]
Definitely!

If we're going to go down the `TTF_SetFontWrappedAlign` path, maybe the constants should be named like `TTF_WRAPPED_ALIGN_LEFT`.

**Comment by Starbuck5** [comment]
@slouken Waiting on you for an executive decision on the API 🙂

**Comment by slouken** [comment]
> If we're going to go down the `TTF_SetFontWrappedAlign` path, maybe the constants should be named like `TTF_WRAPPED_ALIGN_LEFT`.

Yep, this renaming sounds good.

**Pull request merged**
