### PR TITLE
Bump vendored harfbuzz from 2.9.1 (August 2021) to 8.1.1 (August 2023)

### PR DESCRIPTION
**Pull request by madebr**
I tested this with Linux and mingw (on Linux).

### CODE REVIEW

**Comment by sezero** [comment]
I'm not really against upgrading our vendored harfbuzz, but the linked issue is apparently doing the wrong thing..

**Comment by sezero** [comment]
BTW, the latest is 8.1.1 not 8.0.1: do you have a specific reason for choosing 8.0.1?

**Comment by madebr** [comment]
> I'm not really against upgrading our vendored harfbuzz, but the linked issue is apparently doing the wrong thing..

Yes and no, he copied the sources of a more recent harfbuzz what this pr solves.
Copying build artifacts over is not supported.

**Comment by madebr** [comment]
> BTW, the latest is 8.1.1 not 8.0.1: do you have a specific reason for choosing 8.0.1?

No, 8.0.1 was on top of my view of gitk I didn't check the harfbuzz directory.

**Comment by sezero** [comment]
> 
>  he copied the sources of a more recent harfbuzz

That _is_ the wrong thing: hat he copied is not _our vendored_ version.

>    what this pr solves.

It will fail to do so if you don't warn him about his mistake where he may
very well attempt to use another different version and fail again.

**Comment by madebr** [comment]
> > he copied the sources of a more recent harfbuzz
> 
> That _is_ the wrong thing: what he copied is not _our vendored_ version.
> 
> > what this pr solves.
> 
> It will fail to do so if you don't warn him about his mistake where he may very well attempt to use another different version and fail again.

I'll remove the mention, and post something about alternative vendored harfbuzz versions not being supported. He should have built harfbuzz himself, and linked to it like a system library.

**Comment by sezero** [comment]
> > > he copied the sources of a more recent harfbuzz
> > 
> > 
> > That _is_ the wrong thing: what he copied is not _our vendored_ version.
> > > what this pr solves.
> > 
> > 
> > It will fail to do so if you don't warn him about his mistake where he may very well attempt to use another different version and fail again.
> 
> and post something about alternative vendored harfbuzz versions not being supported.

Not just harfbuzz in SDL_ttf, but any other external lib in any other SDL satellite lib

> He should have built harfbuzz himself, and linked to it like a system library.

Indeed

**Comment by sezero** [comment]
harfbuzz tagged a new 8.2.2 release, if we're interested.

**Comment by sezero** [comment]
> harfbuzz tagged a new 8.2.2 release, if we're interested.

And they tagged 8.3.0 today - in case we are interested.

**Pull request merged**
