### PR TITLE
Implemented font atlas support for the renderer text engine

### PR DESCRIPTION
**Pull request by slouken**
This turns most text drawing into a single draw call.

### CODE REVIEW

**Comment by sezero** [comment]
```
src/SDL_renderer_textengine.c: In function 'ResolveMissingGlyphs':
src/SDL_renderer_textengine.c:386: warning: passing argument 4 of 'SDL_qsort_r' from incompatible pointer type
/tmp/SDL3/include/SDL3/SDL_stdinc.h:1382: note: expected 'SDL_CompareCallback_r' but argument is of type 'int (*)(const void *, const void *, const void *)'
src/SDL_renderer_textengine.c: In function 'CreateMissingGlyphs':
src/SDL_renderer_textengine.c:459: warning: passing argument 4 of 'SDL_qsort_r' from incompatible pointer type
/tmp/SDL3/include/SDL3/SDL_stdinc.h:1382: note: expected 'SDL_CompareCallback_r' but argument is of type 'int (*)(const void *, const void *, const void *)'
src/SDL_renderer_textengine.c: At top level:
src/stb_rect_pack.h:229: warning: ‘stbrp_setup_heuristic’ defined but not used
```

**Comment by sezero** [comment]
Trivial build fix for sort callback:

```diff
diff --git a/src/SDL_renderer_textengine.c b/src/SDL_renderer_textengine.c
--- a/src/SDL_renderer_textengine.c
+++ b/src/SDL_renderer_textengine.c
@@ -86,5 +86,5 @@ typedef struct TTF_RendererTextEngineData
 
 
-static int SDLCALL SortMissing(const void *userdata, const void *a, const void *b)
+static int SDLCALL SortMissing(void *userdata, const void *a, const void *b)
 {
     const TTF_DrawOperation *ops = (const TTF_DrawOperation *)userdata;
```

Didn't touch stb header. (Its permissions need changing to 0644, btw...)

**Comment by slouken** [comment]
Fixed!

**Comment by sezero** [comment]
About stb_rect_pack.h: There is [this open PR at mainstream](https://github.com/nothings/stb/pull/1299) you might want to include.

**Comment by sezero** [comment]
You may also want to do this:

```diff
diff --git a/src/SDL_renderer_textengine.c b/src/SDL_renderer_textengine.c
index 9b707e4..4aa1093 100644
--- a/src/SDL_renderer_textengine.c
+++ b/src/SDL_renderer_textengine.c
@@ -29,4 +29,5 @@
 #define STBRP_SORT SDL_qsort
 #define STBRP_ASSERT SDL_assert
+#define STBRP__CDECL SDLCALL
 #include "stb_rect_pack.h"
 
diff --git a/src/stb_rect_pack.h b/src/stb_rect_pack.h
index 6a633ce..099b132 100644
--- a/src/stb_rect_pack.h
+++ b/src/stb_rect_pack.h
@@ -216,9 +216,14 @@ struct stbrp_context
 #ifdef _MSC_VER
 #define STBRP__NOTUSED(v)  (void)(v)
-#define STBRP__CDECL       __cdecl
 #else
 #define STBRP__NOTUSED(v)  (void)sizeof(v)
+#endif
+#ifndef STBRP__CDECL
+#ifdef _MSC_VER
+#define STBRP__CDECL       __cdecl
+#else
 #define STBRP__CDECL
 #endif
+#endif /* STBRP__CDECL */
 
 enum
```

**Comment by slouken** [comment]
Good call, I'll pull them in shortly.

**Pull request merged**
