### PR TITLE
Add casts to ARM NEON code

### LINKED ISSUE #405: Errors when building from source on aarch64 Linux
I'm building the SDL3 versions of the libraries I want to use on an odd aarch64 Ubuntu system.
If you know about Termux, you'll understand what I mean if I say it's an Ubuntu proot.

I don't know anything about how this works, so I'll just drop the logs here

Don't be surprised if I don't answer right away, it's 9pm and I gotta sleep

[sdl ttf errors.txt](https://github.com/user-attachments/files/17283480/sdl.ttf.errors.txt)

### PR DESCRIPTION
**Pull request by madebr**
The code was switching between  uint8x16_t <-> uint16x8_t <-> uint32x4_t, without casts

Fixes #405

### CODE REVIEW

**Review by slouken — APPROVED** [review]
This _seems_ fine to me... @1bsyl?

**Comment by 1bsyl** [comment]
@madebr @slouken , I've tried and this seems ok to me!

**Comment by slouken** [comment]
Great, thanks!

**Comment by sezero** [comment]
Is SDL2 branch OK?

**Comment by slouken** [comment]
Yep, @madebr or @sezero, if you can cherry-pick to main that would be great.

**Comment by madebr** [comment]
I cherry-picked this commit in a3d0895

**Pull request merged**
