### PR TITLE
ci: setup ninja through aseprite/get-ninja action

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by sezero** [comment]
Why is this not in ?

**Comment by madebr** [comment]
> Why is this not in ?

I didn't find the merge button :)

**Comment by sezero** [comment]
Apply to SDL2 branch too?

**Comment by madebr** [comment]
> Apply to SDL2 branch too?

It's already in there https://github.com/libsdl-org/SDL_ttf/commit/b4969dc0ef6453e90fdaf66d143ddd6c8ea6424c

This pr lingering around was literally me not finding the merge button :)

**Comment by sezero** [comment]
> This pr lingering around was literally me not finding the merge button :)

Eh? You really weren't joking ?

**Pull request merged**
