### PR TITLE
Fix workaround causing issues on static builds

### PR DESCRIPTION
**Pull request by object71**

### CODE REVIEW

**Comment by sezero** [comment]
@madebr ?

**Comment by madebr** [comment]
@object71 

Hi!
I've just created https://github.com/libsdl-org/SDL_ttf/pull/213 that solves this in a very similar but slightly different way.
Can you please test that one and check whether your static build error goes away?

**Comment by object71** [comment]
> @object71
> 
> Hi! I've just created #213 that solves this in a very similar but slightly different way. Can you please test that one and check whether your static build error goes away?

Works. I had a similar issue with SDL_image too

**Comment by madebr** [comment]
Thanks for checking!
I'm currently reworking the cmake build systems of SDL_image, SDL_mixer and SDL_ttf.
In the end, all should follow the same pattern and behave in the same way.

**Comment by object71** [comment]
@madebr Okay, closing my pull requests then

**Pull request closed without merging**
