### PR TITLE
Bump freetype dependency to 2.13.0 [SDL2]

### PR DESCRIPTION
**Pull request by madebr**
SDL2 equivalent of https://github.com/libsdl-org/SDL_ttf/pull/275

### CODE REVIEW

**Comment by sezero** [comment]
`.gitmodules` file still says `VER-2-12-1-SDL` as the branch.

Are your cmake patches in `VER-2-12-1-SDL` branch, i.e. https://github.com/libsdl-org/freetype/commit/61cf81001ae77ba40390323477abaf398847b99e and https://github.com/libsdl-org/freetype/commit/7c0a9b0829cb2dc4a907924e89d691f69b4b3ff9 not needed anymore in the new `VER-2-13-0-SDL`?

(Same questions for the SDL3 version.)

**Comment by madebr** [comment]
Fixed `.gitmodules`.
I still see those CMake patches in VER-2-13-0-SDL: https://github.com/libsdl-org/freetype/commit/7aa2fa691b16ef8a147680418bad7a84624fc3ae and https://github.com/libsdl-org/freetype/commit/9d177c718efa2a7b63e3ce4e4c1e837bdd0d0cde

**Comment by sezero** [comment]
P.S.: You may also want https://github.com/libsdl-org/freetype/commit/3f2ac7d890941b747794cbdbf9a08aa3ec667c3d (and maybe https://github.com/libsdl-org/freetype/commit/09b326fa2b3198e462fc75f98973981f23ec7382) in the `VER-2-13-0-SDL` branch. (There is also https://github.com/libsdl-org/freetype/commit/79c8bd91100af8d1b8df82269815a95ca1e91ead but I can't remember whether we are building ftgzip.c)

**Comment by madebr** [comment]
`ftgzip.c` is built via the cmake script + android.mk, so I added that patch.

**Pull request merged**
